AWSTemplateFormatVersion: 2010-09-09
Description: |
  cloudformation template for the infrastructure of pweb application that consist: - RDS Database. - Elasticache cluster  - S3 bucket  - Cloudfront distribution - Autoscaling Group  - Elastic Loadbalancer
Parameters:
  ClusterName:
    Type: String
    Description: Enter your cluster name
  ApplicationDesiredCount:
    Type: Number
    Description: Desired EC2 instance count
  ApplicationSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Target subnets for Ec2 instances
  PwebAmiId:
    Description: Region specific image from the Parameter Store
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  PwebInstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.meduim
      - t3.large
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: ECS instances's key pair 
Resources:
  PwebCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
  PwebAutoscalingLauchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LauchTemplateName: !Sub ${AWS::StackName}-lauch-template
      LauchTemplateData:
        ImageId: !Ref PwebAmiId
        InstanceType: !Ref PwebInstanceType
        KeyName: !Ref KeyName
        SecurityGroups: null
        IamInstanceProfile: null
  PwebAutoscaling:
    Type: AWS::AutoScaling::AutoscalingGroup
    Properties:
      LauchTemplate:
        LauchTemplateId: !Ref PwebAutoscalingLauchTemplate
        Version: !GetAtt PwebAutoscalingLauchTemplate.LatestVersionNumber
      DesiredCapacity: !Ref ApplicationDesiredCount
      LaunchConfigurationName: !Ref PwebAutoscalingLauchConfiguration
      MaxSize: 4
      MinSize: 1
      VPCZoneIdentifier: !Ref ApplicationSubnets
 # Pweb elastic load balancer     
  PwebALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes: 
        - Key: idle_timeout.timeout_seconds
          Value : 30
      Name: !Sub ${AWS::StackName}-elastic-loadbalancer
      Scheme: internet-facing
      SecurityGroups: !Ref PwebALBSecurityGroup
      Subnets: !Ref ApplicationSubnets
  # Pweb elastic load balancer security group
  PwebALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: String
      GroupName: String
      SecurityGroupEgress: 
        - Egress
      SecurityGroupIngress: 
        - Ingress
      Tags: 
        - Tag
      VpcId: String
    

Outputs: null