---
# Copyright 2023 franck fesse
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: 2010-09-09
Description: ECS task definition

Parameters:
  FamilyName:
    Description: Task Family Name
    Type: String
  TaskMemory:
    Description: Task total Memory
    Type: String
    Default: 0.5GB
  TaskCPU:
    Description: Task total Cpu
    Type: String
    Default: 256  
  ContainerPort:
    Type: Number
    Default: 80  
  HostPort:
    Type: Number
    Default: 80  
  ContainerName:
    Type: String
  ContainerImage:
    Type: String
    Default: 012345678901.dkr.ecr.region.amazonaws.com/image:tag
  EssentialContainer:
    Type: String
    AllowedValues:
      - true
      - false
    Default: true    




Resources:
  MyTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions: 
        - Name: !Ref ContainerName
          Image: !Ref ContainerImage
          Essential: !Ref EssentialContainer
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: !Ref HostPort

      Cpu: !Ref TaskCPU
      ExecutionRoleArn: !Ref ExecutionRole
      Family: !Ref FamilyName
      Memory: !Ref TaskMemory
      NetworkMode: awsvpc
      RequiresCompatibilities: 
        - FARGATE
      RuntimePlatform: 
        RuntimePlatform
      Tags: 
        - Tag
      TaskRoleArn: !Ref TaskRole
      Volumes: 
        - Volume
#Role needed by the task
  Taskrole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: Json
      Description: String
      ManagedPolicyArns: 
        - String
      MaxSessionDuration: Integer
      Path: String
      PermissionsBoundary: String
      Policies: 
        - Policy
      RoleName: String
      Tags: 
        - Tag

#Role for containers
ExecutionRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument: Json
    Description: String
    ManagedPolicyArns: 
      - String
    MaxSessionDuration: Integer
    Path: String
    PermissionsBoundary: String
    Policies: 
      - Policy
    RoleName: String
    Tags: 
      - Tag
